CREATE TABLE user(
    username VARCHAR(12) NOT NULL,
    password VARCHAR(255) NOT NULL,
    salt BINARY(32) NOT NULL,
    primary key(username)
);

CREATE TABLE hand(
    id BIGINT NOT NULL AUTO_INCREMENT,
    card_id BIGINT,
    FOREIGN KEY (card_id) REFERENCES card (id),
    PRIMARY KEY (id)
);

CREATE TABLE card(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    RANK  VARCHAR(50) NOT NULL,
    SUIT  VARCHAR(50) NOT NULL,
    HAND_ID BIGINT,
    FOREIGN KEY (HAND_ID) REFERENCES HAND (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE game_history(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    RESULT  VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(12),
    FOREIGN KEY (USER_ID) REFERENCES USER (username),
    PRIMARY KEY (ID)
);