CREATE TABLE user(
    username VARCHAR(12) NOT NULL,
    password VARCHAR(255) NOT NULL,
    salt BINARY(32) NOT NULL,
    primary key(username)
);

CREATE TABLE hand(
    id BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id)
);

CREATE TABLE card(
    id BIGINT NOT NULL AUTO_INCREMENT,
    rank  VARCHAR(50) NOT NULL,
    suit  VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE game_history(
    id BIGINT NOT NULL AUTO_INCREMENT,
    result  VARCHAR(50) NOT NULL,
    WINROUND BOOLEAN,
    GAMEDATE DATE,
    USER_ID VARCHAR(12),
    FOREIGN KEY (USER_ID) REFERENCES USER (username),
    PRIMARY KEY (id)
);